/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\Fridge.glb --keepgroups 
*/

import { useGLTF, useAnimations } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'
import { forwardRef, useImperativeHandle } from 'react';
import * as THREE from "three";
import { GLTF } from 'three-stdlib';

// Fix: Use type instead of interface for FridgeProps
// and use type assertion for needsUpdate

type FridgeProps = JSX.IntrinsicElements['group'] & {
  onRefsReady: (ref: React.RefObject<THREE.Mesh>, name: string) => void;
};

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
};

const Fridge = React.forwardRef<
  { handleAnimation: (action: string) => void },
  FridgeProps
>((props, ref) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    'https://nrfofydoketfepkipdst.supabase.co/storage/v1/object/sign/threedconfigurator/Fridge.glb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InN0b3JhZ2UtdXJsLXNpZ25pbmcta2V5XzU3NDY4ODg5LWUzMGYtNGU5Yy1hYTUxLTcwZDIyM2U4MWFlNiJ9.eyJ1cmwiOiJ0aHJlZWRjb25maWd1cmF0b3IvRnJpZGdlLmdsYiIsImlhdCI6MTc0NjAzMzI5MiwiZXhwIjoyMDYxMzkzMjkyfQ.mwr6elCtSLooE80fapMZQ2U0YDwzDq_qUqmv1p0ZCRU'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  // Track animation states for each action (false = closed, true = open)
  const animationStates = useRef<Record<string, boolean>>({});
  const materialRef = useRef<THREE.Mesh>(null);
  const handleAnimation = (action: string) => {
    // console.log(action)
    if (actions[action]) {
      // Initialize state for this action if not already set
      if (animationStates.current[action] === undefined) {
        animationStates.current[action] = false;
      }
      
      const isOpen = animationStates.current[action];
      const currentAction = actions[action];
      
      // Configure animation to play once and hold at the end
      currentAction.setLoop(THREE.LoopOnce, 0);
      currentAction.clampWhenFinished = true;
      
      // Stop any current playback
      currentAction.stop();
      
      if (isOpen) {
        // Play in reverse: set negative timeScale and start from end
        currentAction.timeScale = -1;
        currentAction.time = currentAction.getClip().duration;
      } else {
        // Play forward: reset to beginning and use positive timeScale
        currentAction.timeScale = 1;
        currentAction.time = 0;
      }
      
      // Play the animation
      currentAction.play();
      
      // Toggle the state for next click
      animationStates.current[action] = !isOpen;
    }
  };

  useImperativeHandle(ref, () => ({
    handleAnimation,
  }));

  useEffect(() => {
    props.onRefsReady(materialRef, 'fridge');
    // if (materialRef?.current) {
    //   // Remove texture map if present
    //   if (materialRef.current.material && 'map' in materialRef.current.material) {
    //     (materialRef.current.material as any).map = null;
    //     (materialRef.current.material as any).needsUpdate = true;
    //   }
    // }
    // material
  }, [materialRef, props]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Body">
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['Outer body']} ref={materialRef} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials['Inner body']} />
          <group name="Left_Door" position={[-0.446, 1.771, 0.374]} rotation={[0, Math.PI / 2, 0]}>
            <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials['Outer body']} />
            <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials['Inner body']} />
            <mesh name="Mesh010_2" geometry={nodes.Mesh010_2.geometry} material={materials.Samsung_Fridge} />
            <mesh name="Left_Door_Handle" geometry={nodes.Left_Door_Handle.geometry} material={materials['Outer body']} position={[-0.124, -0.538, 0.41]} />
            <mesh name="Left_Door_Hinge" geometry={nodes.Left_Door_Hinge.geometry} material={materials.Samsung_Fridge} position={[-0.008, -0.013, 0.016]} />
            <mesh name="Left_Door_Shelves" geometry={nodes.Left_Door_Shelves.geometry} material={materials.Glass} position={[-0.01, -0.815, 0.209]} rotation={[-Math.PI, 0, -Math.PI]} />
          </group>
          <group name="Refregerator" position={[0, 0.006, 0.459]}>
            <mesh name="Mesh007" geometry={nodes.Mesh007.geometry} material={materials['Outer body']} />
            <mesh name="Mesh007_1" geometry={nodes.Mesh007_1.geometry} material={materials['Inner body']} />
            <mesh name="Refregerator_Handle" geometry={nodes.Refregerator_Handle.geometry} material={materials['Outer body']} position={[0, 0.582, 0.034]} />
            <mesh name="Refregerator_Support" geometry={nodes.Refregerator_Support.geometry} material={materials['Outer body']} position={[-0.338, 0.6, -0.024]} />
          </group>
          <group name="Right_Door" position={[0.448, 1.771, 0.374]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh name="Mesh014" geometry={nodes.Mesh014.geometry} material={materials['Outer body']} />
            <mesh name="Mesh014_1" geometry={nodes.Mesh014_1.geometry} material={materials['Inner body']} />
            <mesh name="Right_Door_Handle" geometry={nodes.Right_Door_Handle.geometry} material={materials['Outer body']} position={[0.113, -0.538, 0.417]} />
            <mesh name="Right_Door_Hinge" geometry={nodes.Right_Door_Hinge.geometry} material={materials.Samsung_Fridge} position={[0.008, -0.013, 0.016]} />
            <mesh name="Right_Door_Shelves" geometry={nodes.Right_Door_Shelves.geometry} material={materials.Glass} position={[0.004, -0.265, 0.23]} />
          </group>
          <mesh name="Interior_Drawner" geometry={nodes.Interior_Drawner.geometry} material={materials.Glass} position={[0, 0.962, -0.264]} />
          <mesh name="Interior_Drawner001" geometry={nodes.Interior_Drawner001.geometry} material={materials['Inner body']} position={[-0.001, 0.799, -0.235]} />
          <mesh name="Interior_IceMaker" geometry={nodes.Interior_IceMaker.geometry} material={materials['Inner body']} position={[-0.329, 1.555, -0.194]} />
          <mesh name="Interior_Light_Left" geometry={nodes.Interior_Light_Left.geometry} material={materials.Light} position={[-0.403, 1.225, 0.215]} rotation={[0, 0, Math.PI / 2]} />
          <mesh name="Interior_Light_Right" geometry={nodes.Interior_Light_Right.geometry} material={materials.Light} position={[0.405, 1.225, 0.215]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          <mesh name="Interior_Light_Top" geometry={nodes.Interior_Light_Top.geometry} material={materials.Light} position={[0, 1.696, 0.044]} />
          <group name="Interior_Shelves" position={[0, 1.061, -0.264]}>
            <mesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials['Inner body']} />
            <mesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials.Glass} />
          </group>
          <mesh name="Interior_Support" geometry={nodes.Interior_Support.geometry} material={materials.Samsung_Fridge} position={[-0.001, 0.799, -0.235]} />
          <mesh name="Left_Door_Support" geometry={nodes.Left_Door_Support.geometry} material={materials.Samsung_Fridge} position={[-0.406, 1.742, 0.354]} />
          <mesh name="Right_Door_Support" geometry={nodes.Right_Door_Support.geometry} material={materials.Samsung_Fridge} position={[0.408, 1.742, 0.354]} />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload('https://nrfofydoketfepkipdst.supabase.co/storage/v1/object/sign/threedconfigurator/Fridge.glb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InN0b3JhZ2UtdXJsLXNpZ25pbmcta2V5XzU3NDY4ODg5LWUzMGYtNGU5Yy1hYTUxLTcwZDIyM2U4MWFlNiJ9.eyJ1cmwiOiJ0aHJlZWRjb25maWd1cmF0b3IvRnJpZGdlLmdsYiIsImlhdCI6MTc0NjAzMzI5MiwiZXhwIjoyMDYxMzkzMjkyfQ.mwr6elCtSLooE80fapMZQ2U0YDwzDq_qUqmv1p0ZCRU');

export { Fridge };
